#!/bin/bash
make clean
make
cmd.exe /C qemu-x86_64.bat
# /mnt/c/Program\ Files\ \(x86\)/qemu-0.10.4/qemu-system-x86_64.exe -L "C:\Program Files (x86)\qemu-0.10.4" -m 64 -fda Disk.img -boot a -localtime -M pc -serial tcp::4444,server,nowait -smp 2

